Rania\SSSBundle\Entity\Cart:
    type: entity
    table: null
    repositoryClass: Rania\SSSBundle\Entity\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: string
            length: 255
    manyToOne:
     items:
      targetEntity: Item
      inversedBy: Cart
      joinColumn:
        name: item_ids
        referencedColumnName: id
   
    lifecycleCallbacks: {  }
