Rania\SSSBundle\Entity\Item:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        stockQuantity:
            type: integer
        ownerId:
            type: string
            length: 255
    oneToMany:
        cart:
          targetEntity: Cart
          mappedBy: Item
          cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
